import asyncio
import logging
import requests
import random
from aiogram import Bot
from apscheduler.schedulers.asyncio import AsyncioScheduler

# --- ТВОИ ДАННЫЕ УЖЕ ТУТ ---
API_TOKEN = '8309438145:AAEGBACLyLh2H_OyUk6ScDYpvNJU9_OaQyQ'
CHANNEL_ID = '@iPromt_AI'
POSTS_PER_DAY = 20
INTERVAL_SECONDS = (24 * 60 * 60) // POSTS_PER_DAY # Примерно каждые 72 минуты

logging.basicConfig(level=logging.INFO)
bot = Bot(token=API_TOKEN)
scheduler = AsyncioScheduler()

# База данных в памяти, чтобы не постить одно и то же за один сеанс
posted_urls = set()

def get_ai_content():
    # Ищем на Reddit в топовых сообществах по нейросетям
    subreddits = ['midjourney', 'StableDiffusion', 'DALL-E']
    sub = random.choice(subreddits)
    url = f"https://www.reddit.com/r/{sub}/hot.json?limit=50"
    headers = {'User-agent': 'AI-Prompt-Bot-v1'}
    
    # Ключевые слова для поиска людей/пар
    keywords = ['woman', 'man', 'couple', 'girl', 'boy', 'portrait', 'people', 'love', 'model', 'human']
    
    try:
        response = requests.get(url, headers=headers).json()
        posts = response['data']['children']
        random.shuffle(posts)
        
        for post in posts:
            data = post['data']
            title = data['title'].lower()
            img_url = data.get('url', '')
            
            # Проверка: это картинка, мы ее еще не постили и там есть люди
            if img_url.endswith(('.jpg', '.png', '.jpeg')) and img_url not in posted_urls:
                if any(word in title for word in keywords):
                    posted_urls.add(img_url)
                    return img_url, data['title']
    except Exception as e:
        logging.error(f"Ошибка при поиске контента: {e}")
    return None, None

async def post_now():
    image, prompt = get_ai_content()
    if image:
        try:
            caption = f"🎨 **Prompt:** {prompt}\n\n🤖 Generated by AI\n📍 Source: Reddit\n\n#ai #prompts #art #people"
            await bot.send_photo(chat_id=CHANNEL_ID, photo=image, caption=caption, parse_mode="Markdown")
            logging.info(f"Опубликовано в {CHANNEL_ID}")
        except Exception as e:
            logging.error(f"Ошибка отправки в Telegram: {e}")

async def main():
    # Сразу делаем первый пост при запуске
    await post_now()
    
    # Запускаем таймер на 20 постов в день
    scheduler.add_job(post_now, 'interval', seconds=INTERVAL_SECONDS)
    scheduler.start()
    
    # Поддерживаем работу скрипта
    while True:
        await asyncio.sleep(3600)

if __name__ == '__main__':
    try:
        asyncio.run(main())
    except (KeyboardInterrupt, SystemExit):
        pass